### PR TITLE
Handle config via a dataclass

### PR DESCRIPTION
**Pull request by tarkatronic**
This is the first step in a major code cleanup working toward v2.0.

It is loosely based on the discussion in #23, and is a big step in the work toward #39.

Basically now instead of dissecting and passing parts of a dictionary around piecemeal, the config is all handled through these new `Options` dataclasses. The idea is that, when #39 is implemented, each type of scanner will implement its own new `Options` dataclass, hence the split between `BaseOptions` and `GitOptions`.

This also resulted in a very nice reduction of LOC. A net of just over -100 lines!

### CODE REVIEW

**Comment by beardedeagle** [comment]
looking

**Comment by beardedeagle** [comment]
Cursory glance looks good, digging deeper before giving all clear.

**Review by beardedeagle — APPROVED** [review]
LGTM

**Review by janerikcarlsen — APPROVED** [review]
The change looks great 🔥

**Pull request merged**
