### PR TITLE
allow exclude-entropy-patterns to match lines containing partial matches

### LINKED ISSUE #217: Entropy exclusion regexes don't look at surrounding text
## 🐛 Bug Report

Currently, the [--exclude-entropy-patterns](https://tartufo.readthedocs.io/en/stable/features.html#entropy-limiting) feature only allows you to exclude based on the exact matched string, rather than being able to match based on the surrounding text. This means that, as an example, I cannot explicitly exclude just SHA hashes in GitHub actions.

## To Reproduce

1. Set up a GitHub Action using a SHA hash, such as:
    
    ```yaml
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    ```

1. Set up an exclusion pattern that [should match this](https://pythex.org/?regex=%5E%5Cs%2B(%3F%3A-%20)%3Fuses%5C%3A%20actions%5C%2F.*%5C%40%5Ba-z0-9%5D%7B40%7D%24&test_string=%20%20%20%20%20-%20uses%3A%20actions%2Fcheckout%405a4ac9002d0be2fb38bd78e4b4dbde5606d7042f%0A%20%20%20%20%20%20%20uses%3A%20actions%2Fsetup-python%40dc73133d4da04e56a135ae2246682783cc7c7cb6%0A%20%20%20%20%20-%20uses%3A%20actions%2Fcache%40c64c572235d810460d0d6876e9c705ad5002b353%0A&ignorecase=0&multiline=1&dotall=0&verbose=0):
   
   ```toml
   exclude-entropy-patterns = [
       '.github/workflows/(.*)\.yml::^\s+(?:- )?uses\: actions\/.*\@[a-z0-9]{40}$'
   ]
   ```

1. Run a scan.

## Expected Behavior

There should be no match in the scan.

## Potential Cause / Fix

It appears that the issue stems from the way that entropy is evaluated, here: https://github.com/godaddy/tartufo/blob/ee84de8d6754a470d2777418bd2f9b895dd54211/tartufo/scanner.py#L355-L374

Specifically:
* A "chunk" is split into individual lines.
* Those lines are split into individual words.
* Those words are split into "strings".
* Those "strings" are evaluated for their entropy value.
* Exclusion matching is performed based solely on the "strings" themselves.

So when an individual "string" is evaluated, it has no visibility to the line, or even the word, from which it was extracted. It seems that the solution would be to pass along either the word or the line from which the string was extracted, and perform exclusion matching on that value instead.

### PR DESCRIPTION
**Pull request by kbartholomew-godaddy**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [X] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [X] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [X] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [X] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking

fixes #217 

## What's new?
- `ScannerBase.evaluate_entropy_string` now evaluates the entire line and uses `re.search()` when determining if an entropy string is included, so that false positives can be excluded based on their context.

   For example, `--exclude-entropy-patterns 'file.txt::falsePositive: [a-f0-9]{40}'` will exclude line 1 of this file but not line 2:

   ```yaml
   falsePositive: abcdef0123456789abcdef0123456789abcdef01
   realSecret: abcdef0123456789abcdef0123456789abcdef01
   ```

### CODE REVIEW

**Review by sjacoby-godaddy — APPROVED** [review]

**Review by tarkatronic — APPROVED** [review]
This is great @kbartholomew-godaddy; thanks for doing the work on this! I'm excited to see this feature become SO much more useful now!

**Comment by wberry-godaddy** [comment]
Double checking, but this hasn't been released yet — correct?

**Comment by tarkatronic** [comment]
@wberry-godaddy That would be correct; apologies for the delay. Processing the v2.8.1 release here: https://github.com/godaddy/tartufo/pull/224

**Comment by wberry-godaddy** [comment]
Thanks @tarkatronic, much appreciated

**Pull request merged**
