### PR TITLE
Set up the beginning of logging

### LINKED ISSUE #76: Add logging to tartufo
## Is your feature request related to a problem? Please describe.

It's hard to see into what `tartufo` is doing because right now there is no logging available anywhere. This also makes debugging errors much more difficult. Even as I'm working on development, I usually do shotgun print debugging, wishing I could just add a debug log message.

## Describe the solution you'd like

* There should be log message liberally sprinkled throughout the code base with appropriate log levels (info, debug, warning, error).
* There should be a `-v/--verbose` option, which can be repeated for extra verbosity (-vvv), AND/OR a `-l LOGLEVEL` for example `-l info` to specify desired log level
* There should be a `-q/--quiet` option if there is default output, which mutes all output

One possibility I've looked at that might make this easier is [click-log](https://github.com/click-contrib/click-log).

This might also help with #37, #42, and #43.

Given a thorough implementation this could also help with #11.

### PR DESCRIPTION
**Pull request by tarkatronic**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [x] Tests (if applicable)
* [x] Documentation (if applicable)
* [x] Changelog entry
* [X] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [X] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [X] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking

Fixes #76 

## What's new?

The goal here is to provide a starting point for logging. I figured this was good to add now as we're starting to get more users, and getting bug reports. The output from this logging could be very helpful in figuring out their issues.

This is a draft PR for now, to get the conversation started on this. I want to be sure I'm logging the right things, at the right levels. I think I may even add more debug logging around what commits are being scanned, but we'll see. Please, let me know what you think.

Another part I would like to add as I progress in this is, amending the bug report issue template to ask for a link to a GitHub gist with the output of `-vv` or `-vvv`. The trouble with this is I could see that output easily containing sensitive information. So, probably a fine line to walk there.

### CODE REVIEW

**Comment by tarkatronic** [comment]
@jgowdy Since you've done a good bit of digging into the internals of this library, are there any places in particular you would like to see logging added? I was figuring this would be a good help with the `pygit2` work, whenever that kicks off again.

**Comment by tarkatronic** [comment]
Example output so far:

```console
$ tartufo -vv scan-local-repo .
Initializing excluded paths
Initializing regex rules
Starting scan...
Scanning branch: all-the-pythons
Initializing included paths
pyproject.toml excluded - matched excluded paths
.github/workflows/ci.yml excluded - matched excluded paths
poetry.lock excluded - matched excluded paths
tests/test_base_scanner.py excluded - matched excluded paths
tests/test_util.py excluded - matched excluded paths
.github/workflows/publish.yml excluded - matched excluded paths
docs/source/api.rst excluded - matched excluded paths
docs/source/changelog.rst excluded - matched excluded paths
docs/source/configuration.rst excluded - matched excluded paths
docs/source/examplecleanup.rst excluded - matched excluded paths
docs/source/features.rst excluded - matched excluded paths
docs/source/index.rst excluded - matched excluded paths
docs/source/installation.rst excluded - matched excluded paths
docs/source/usage.rst excluded - matched excluded paths
.github/workflows/codeql-analysis.yml excluded - matched excluded paths
Scanning branch: bugfix-115
Scanning branch: bugfix-117
Scanning branch: bugfix-140
Scanning branch: burgessa23/main
Scanning branch: config-class
Scanning branch: document-releases
```

**Comment by jgowdy** [comment]
Would definitely love to see any logging we can do about auth, like what auth mechanism is being used etc.  Not sure if we get that from GitPython and its use of git CLI.  I think we should have a high verbosity logging mode that literally shows the hashes that are being scanned, in the order they're being scanned.  I could see this having value in integration testing with one or more sample repos which I think we want to get to.  That would ensure we don't have a regression that starts missing branches or something.

**Review by jgowdy — APPROVED** [review]

**Review by sjacoby-godaddy — APPROVED** [review]
looks good!

**Review by jgowdy — APPROVED** [review]

**Pull request merged**
