### PR TITLE
Handle the case where exclude-signatures is a list of strings

### LINKED ISSUE #371: `update-signatures` fails with some tartufo configs
## 🐛 Bug Report

It cannot parse a config like this:

```toml
[tool.tartufo]
exclude-signatures = [
    "abc",
    "def",
]
```

## To Reproduce

run `tartufo update-signatures .` on a local repo with a config like the above.

## Expected Behavior

The config should be handled regardless of whether it's a list of strings, or a list of dictionaries.

### LINKED ISSUE #373: click.echo fails when passed bytes
## 🐛 Bug Report

There appears to be some bug in `click`, where it is unable to print bytes even thought it is typed as accepting bytes.
We explicitly convert a scanner to bytes before echoing it - which causes a bug in the update-signatures command on some configs - I havent found the exact cause of the issue however. 

## To Reproduce

Reproduction is unreliable, I've been able to reproduce by copying an internal config that was having this issue.
This is resolved by passing a string instead of bytes to click.echo

## Expected Behavior

The update signatures command will run.

## Actual result

```
$ python -m tartufo update-signatures .
Traceback (most recent call last):
  File "/Users/jonx/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jonx/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jonx/projects/tartufo/tartufo/__main__.py", line 5, in <module>
    cli.main()  # pylint: disable=no-value-for-parameter
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jonx/projects/tartufo/tartufo/commands/update_signatures.py", line 245, in main
    scanner, stderr = scan_local_repo(
  File "/Users/jonx/projects/tartufo/tartufo/commands/update_signatures.py", line 71, in scan_local_repo
    util.process_issues(repo_path, scanner, options)
  File "/Users/jonx/projects/tartufo/tartufo/util.py", line 265, in process_issues
    echo_result(options, scan, repo_path, output_dir)
  File "/Users/jonx/projects/tartufo/tartufo/util.py", line 107, in echo_result
    click.echo(bytes(issue))
  File "/Users/jonx/projects/tartufo/.venv/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
TypeError: string argument expected, got 'bytes'
```
## Environment

Tartufo version 3.2.1
MacOS Monterey 12.4
Python 3.10.2

### PR DESCRIPTION
**Pull request by jhall1-godaddy**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [x] Tests (if applicable)
* [ ] Documentation (if applicable)
* [x] Changelog entry
* [x] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [x] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking

Closes #371 
Closes #373 

## What's new?

I added an upwrap function to handle the case where `exclude-signatures` is a list of strings. 
I also added additional error handling for the case when there is no config file/no `tool.tartufo` section.

`tomlkit` 0.7.2, the current version in use by `tartufo`, had a bug where values would not update properly.
I created a minimal reproducible example of that:

```py
import tomlkit

toml_content = """
items = [
    "a",
    "c"
]
"""

data = tomlkit.loads(toml_content)
for i, item in enumerate(data["items"]):
    if item == "c":
        data["items"][i] = "b"

print(data["items"])
print([*data["items"]])
```

Result:
```
['a', 'c']
['a', 'b']
```

Expected result:
```
['a', 'b']
['a', 'b']
```

Based on this I updated `tomlkit` to the latest version 0.11.1 and that issue is now resolved.
I added a couple more tests to handle the new cases.

### CODE REVIEW

**Comment by jhall1-godaddy** [comment]
Turns out the docker build was failing because poetry decided to delete half the hashes from the lockfile while updating tomlkit. 
Resolved now.

**Comment by jhall1-godaddy** [comment]
There is a new issue that was experienced relating to trying to pass bytes to click.echo.
I haven't fully determined why this happens, but changing from a `bytes()` call to a `str()` call should resolve it. I will confirm that later. 

Here is the relevant part of the traceback:

```
  File ".../tartufo/util.py", line 265, in process_issues
    echo_result(options, scan, repo_path, output_dir)
  File ".../tartufo/util.py", line 107, in echo_result
    click.echo(bytes(issue))
  File ".../click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
TypeError: string argument expected, got 'bytes'
```

**Review by rbailey-godaddy — APPROVED** [review]
Nice catch. Any particular motivation for modifying the configuration file in place instead of just replacing it with a new version like you were doing before? I'm just interested.

**Comment by jhall1-godaddy** [comment]
Are you referring to the `write_updated_signatures` function?

If so, I did it to prevent opening the file twice, which felt inefficient.

**Comment by jhall1-godaddy** [comment]
Ok this PR now addresses both the issue where exclude-signatures is a list of strings, and also where click.echo fails as described in #373 

Am I missing anything?
Should we try to gracefully handle different config misconfigurations, like if it's a list of dictionary's with no `signature` key, or any other potentially invalid configuration? 

I feel like it might be best to try and prevent a traceback from hitting the end user, but it may obscure potentially useful information in the traceback. I'll defer to your feedback on whether that should be added.

**Comment by jhall1-godaddy** [comment]
I have also noticed an issue where if duplicates are removed from the config, the final closing bracket is placed on the preceding line which can cause issues if that preceding line is only a comment after removing duplicates.

It's a pretty niche bug, but I know of at least 1 repository personally that would be affected.
The end user's fix is to just drop the closing bracket to a newline - super simple - but a bug nonetheless.

A tracking issue has been created on the tomlkit repo [here](https://github.com/sdispater/tomlkit/issues/213).

**Review by sushantmimani — APPROVED** [review]

**Review by emayuri-godaddy — APPROVED** [review]

**Pull request merged**
