### PR TITLE
Enable regex scans by default #254

### LINKED ISSUE #254: Enable regex scans by default
## Is your feature request related to a problem? Please describe.

A lot of the useful scans we do are regular expressions, but these are disabled by default. This should not be the case. We should make our best effort to scan everything by default, and require users to disable scans that they don't want.

## Describe the solution you'd like

As of v3.0, the `--regex` flag should default to True.

### PR DESCRIPTION
**Pull request by mdayanc-GoDaddy**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [x] Changelog entry
* [X] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [X] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [X] Yes (backward compatible)
* [ ] No (breaking changes)

## Issue Linking
closes [#254](https://github.com/godaddy/tartufo/issues/254)

## What's new?
- Changed the default value of `"--regex/--no-regex",` to `True` so that by default we have all scans and users can omit the ones they don't like

### CODE REVIEW

**Comment by tarkatronic** [comment]
Hi @mdayanc-GoDaddy, thanks for handling this -- please be sure to add an entry to the changelog for this!

**Comment by sushantmimani** [comment]
This needs to be branched off of `v3.x` branch.

**Review by sushantmimani — CHANGES_REQUESTED** [review]
This needs to be branched off of and merged back into `v3.x`.

**Comment by mdayanc-GoDaddy** [comment]
Need to do a PR from V3.x in order to not to deal with rebasing as the change is only one line.

**Pull request closed without merging**
