### PR TITLE
move type annotations out of comments, bump minimum python version, c…

### LINKED ISSUE #62: Remove support for Python 3.5
Python 3.5 is about to hit EOL.
Python 3.6 is better and generally available.
We already enforce >= 3.6 for `aws-okta-processor`.
Python 3.6 has the shiny happy new dictionary implementation.
Python 3.6 has `blake2` built in, so one fewer external dependency.
Python 3.6 has class variable annotations. We can stop using the comments for type annotations. Yay!

Let's do this.

### PR DESCRIPTION
**Pull request by voldemortensen**
…loses #62

### CODE REVIEW

**Comment by tarkatronic** [comment]
Hey @voldemortensen, thanks for this work; I'm a little jealous you're getting to do this! 😄 This looks amazing and I'm excited to see this go through. I am hoping to wait until #61 is merged before doing this, because it will also allow the removal of an extra dependency I had to add in there (`pyblake2`). Also of note is that the dependency for `black` can be fixed in this PR. Since we will not be supporting Python < 3.6, we no longer have to specify installing that only on >= 3.6!

**Comment by tarkatronic** [comment]
@voldemortensen You've also exposed a shortcoming in the current CI workflow. I know this is unrelated to this particular branch, but would you mind fixing it up? Either here or in another branch would work. It looks like the coverage information never gets sent to Codecov, because you do not have access to the secrets in this repo. It should be possible to solve this by using the `codecov` action, rather than manually installing and running `codecov` like we currently do. You can see an example of how this works here: https://github.com/Facet-MUD-Project/facetjs/blob/master/.github/workflows/node.js.yml#L33-L36

You would just need to change the path to the actual coverage report file. :)

Thanks!

**Comment by voldemortensen** [comment]
@tarkatronic this was a fun one! I'm in no hurry, so waiting for #61 is fine with me.

I've removed the black version restriction and moved over to the codecov action. I'm not sure way the codecov check hasn't passed since the file has been uploaded. Also, it looks like the repo settings are configured to expect the 3.5 test, so that will need to be updated.

**Comment by tarkatronic** [comment]
It occurred to me, this morning, that I was being silly and my logic was completely backwards. This should absolutely go in before #61 so I never have to introduce that new dependency into the main branch. 😄

**Review by tarkatronic — CHANGES_REQUESTED** [review]
This looks great! Just one last thing: If you can run `poetry update` to sync the `pyproject.toml` with the `poetry.lock` file, we can get this merged!

**Comment by voldemortensen** [comment]
@tarkatronic done!

**Comment by tarkatronic** [comment]
@voldemortensen Perfect, thank you! 🙌  I'm not sure what's with the codecov integration not reporting right as a status update... but I'm going to call this good anyhow.

**Review by tarkatronic — APPROVED** [review]

**Pull request merged**
