### PR TITLE
Boolean Flags Update.

### LINKED ISSUE #245: Better defaults for boolean flags
## 🐛 Bug Report

Boolean flags such as `--compact / --no-compact` with `Default: False` is very confusing.

## To Reproduce

`tartufo -h`

## Expected Behavior

Should show `Default: --no-compact` for `--compact / --no-compact` and similar for other boolean flags

### PR DESCRIPTION
**Pull request by aserputov**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [x] Changelog entry
* [x] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [x] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [ ] Yes (backward compatible)
* [x] No (breaking changes)

## Issue Linking

#245 

## What's new?
-New: Boolean Flags

### CODE REVIEW

**Review by rbailey-godaddy — CHANGES_REQUESTED** [review]
Exactly (I think). Could you also fix `--quiet` and `--log-timestamps` further down the file?

**Comment by rbailey-godaddy** [comment]
Unfortunately, I just released the unit tests and they all hate this syntax, so it appears a little more research is needed to find a solution that expresses what we want and is valid...

**Comment by tarkatronic** [comment]
@aserputov With a little more investigation, reading the [change log for `click`](https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0), I found this gem:
> Help for boolean flags with show_default=True shows the flag name instead of True or False. #1538

So it looks like all that needs to be done here is upgrade `click` from 7.x to 8.x!

**Comment by tarkatronic** [comment]
Hi @aserputov I see you've run `poetry update` to update the `poetry.lock`; unfortunately this isn't doing quite what the command sounds like it's doing. Since `click` is specified in our `pyproject.toml` as `click = "^7"`, this means "use any version of click >= 7.0, and < 8.0", and `poetry update` won't change that.

What you will want to do is run `poetry add "click@latest"`, which will actually update that record in the `pyproject.toml`. From there, make sure all of the tests are still passing, and then if you could also update the output of `tartufo --help` in the `README.md`, that would be a huge help!

And finally, please remember to add a note to the `CHANGELOG.md` about this! 😄

**Comment by sushantmimani** [comment]
@aserputov There are 2 failing steps in CI and a few merge conflicts. Can you please fix them?

**Comment by aserputov** [comment]
@sushantmimani yes, I will try to fix it, now.

**Comment by aserputov** [comment]
@sushantmimani I was trying to fix the failed tests, and I think the problem is in the version of python I use. My current v "3.9" and I should've fixed this issue in "3.7". Could you please advise me if I'm correct?

**Comment by aserputov** [comment]
@tarkatronic hey, what do you think about that issue? Do you believe we should complete the updates, or do you have any new plans for it?

**Comment by tarkatronic** [comment]
@aserputov This is still a necessary change for our 3.0 release, so I would love to see this finished soon! You should try updating your branch against the latest `v3.x` and see if the errors are resolved. It looks like really just one test failing in Windows, and we're not seeing these failures in other PRs.

Hopefully it's just that easy of a quick fix!

Also be sure that your CHANGELOG entry gets moved up into the latest `TBD` section. 😄

**Comment by tarkatronic** [comment]
@aserputov I apologize but for the sake of expediency, I will need to take over this change; we are trying to get v3.0 out as quickly as we can, so I need to get this change finished. I will be sure to acknowledge your work in the release notes though! Thank you for working through this up to now.

**Comment by aserputov** [comment]
@tarkatronic thank you.

**Comment by tarkatronic** [comment]
Superseded by #292

**Pull request closed without merging**
