### PR TITLE
Version bump for v2.9.1

### PR DESCRIPTION
**Pull request by mayuriesha**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [ ] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [ ] Yes (backward compatible)
* [ ] No (breaking changes)

## What's new?
-

### CODE REVIEW

**Review by tarkatronic — APPROVED** [review]

**Review by rbailey-godaddy — CHANGES_REQUESTED** [review]
In hindsight, looking for @tarkatronic concurrence... I think I would make the wording ending in L9-10 stronger.

The problem we explicitly set about fixing was that you couldn't say `scan-remote-repo --branch foobar` because the `.branches` collection only had `main` and nothing else, so your branch could never find it. But I think that isn't what got exercised the most (since nobody complained) and doesn't represent the biggest exposure.

What we didn't think about so much is the case of `scan-remote-repo` (without a branch). This is supposed to scan all branches... but as I just mentioned, the only branch it knows about is `main` (or `master` I suppose), so that is the **only** branch it would scan. If you had other branches, and those had secrets, They. Were. Not. Scanned. I just tested this behavior with 2.9.0  (which had one kind of brain damage) and also with 2.2.0 (which had the different brain damage) and with no branch specified, you get no errors *AND* no non-main branches get scanned and you end up with a massive false sense of security. :(

**Comment by rbailey-godaddy** [comment]
FYI the testing cited above was done using this:

```sh
python tartufo/__main__.py --regex --no-entropy scan-remote-repo git@ghc:gdcorp-appservices/tartufo-test.git
```

The `rename-1` branch in that repository has several regex-based secrets that should be discovered, but won't be found by most of the v2 releases.

**Comment by tarkatronic** [comment]
> In hindsight, looking for @tarkatronic concurrence... I think I would make the wording ending in L9-10 stronger.
> 
> The problem we explicitly set about fixing was that you couldn't say `scan-remote-repo --branch foobar` because the `.branches` collection only had `main` and nothing else, so your branch could never find it. But I think that isn't what got exercised the most (since nobody complained) and doesn't represent the biggest exposure.
> 
> What we didn't think about so much is the case of `scan-remote-repo` (without a branch). This is supposed to scan all branches... but as I just mentioned, the only branch it knows about is `main` (or `master` I suppose), so that is the **only** branch it would scan. If you had other branches, and those had secrets, They. Were. Not. Scanned. I just tested this behavior with 2.9.0 (which had one kind of brain damage) and also with 2.2.0 (which had the different brain damage) and with no branch specified, you get no errors _AND_ no non-main branches get scanned and you end up with a massive false sense of security. :(

So... what is your actual proposed change here?

**Comment by mayuriesha** [comment]
Closing this PR as we will be releasing v2.10.0 and this branch was named v2.9.1

**Pull request closed without merging**
